name: Android CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate Keystore File
      env:
        KEY_STORE: ${{ secrets.APP_KEYSTORE_BASE64 }}
      run : |
        echo $KEY_STORE > ./keystore.b64
        base64 -d -i ./keystore.b64 > ./app/partyrun-keystore.jks

    - name: Setup keystore.properties
      env:
        STORE_PASSWORD: ${{ secrets.storePassword }}
        KEY_PASSWORD: ${{ secrets.keyPassword }}
        KEY_ALIAS: ${{ secrets.keyAlias }}
        STORE_FILE: ${{ secrets.storeFile }}
      run: |
        echo storePassword="$STORE_PASSWORD" >> ./keystore.properties
        echo keyPassword="$KEY_PASSWORD" >> ./keystore.properties
        echo keyAlias="$KEY_ALIAS" >> ./keystore.properties
        echo storeFile="$STORE_FILE" >> ./keystore.properties

    - name: Setup local.properties
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        FIREBASE_GOOGLE_CLIENT_ID: ${{ secrets.FIREBASE_GOOGLE_CLIENT_ID }}
        MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        PARTY_RUN_S3_URL: ${{ secrets.S3_URL }}
      run: |
        echo BASE_URL=\"$BASE_URL\" >> ./local.properties
        echo FIREBASE_GOOGLE_CLIENT_ID=\"$FIREBASE_GOOGLE_CLIENT_ID\" >> ./local.properties
        echo MAPS_API_KEY=\"$MAPS_API_KEY\" >> ./local.properties
        echo PARTY_RUN_S3_URL=\"PARTY_RUN_S3_URL\" >> ./local.properties

    - name: Create google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES }}
      run: echo "$GOOGLE_SERVICES_JSON" > ./app/google-services.json

    - name: Setup Gradle and Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        # Only write to the cache for builds on the 'main' and 'develop' branches. (Default is 'main' only.)
        # Builds on other branches will only read existing entries from the cache.
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}
